server:
  port: 8084
  servlet:
    context-path: /

management:
  server:
    port: 8084
  endpoints:
  web:
   exposure:
    include: "*"

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

