server:
  port: 8084
  servlet:
    context-path: /

management:
  server:
    port: 8084
  endpoints:
   web:
    exposure:
     include: "*"

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest